"""`bench2 status` — regenerate docs/STATUS.md, the zero-maintenance progress board.

Every stage is derived, never hand-edited:
    MERGED     designs/<family>/ exists on main
    GENERATED  factory_status.json has instance counts for the family
    QUALIFIED  factory says the difficulty screen passed
    NEEDS_WORK release qualification failed (reason shown)
    RELEASED   family listed in release/<tag>.json

(IN-PROGRESS lives in GitHub's own PR list — we don't duplicate it.)
Release automation writes `factory_status.json` as a summary of counts and
qualification results.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

TARGET = 300


def generate(root: Path) -> str:
    designs = sorted(
        d.name for d in (root / "designs").iterdir()
        if d.is_dir() and (d / "family.json").exists()
    )
    meta = {n: json.loads((root / "designs" / n / "family.json").read_text()) for n in designs}
    fs_path = root / "factory_status.json"
    factory = json.loads(fs_path.read_text()) if fs_path.exists() else {}
    released: set[str] = set()
    rel_dir = root / "release"
    if rel_dir.is_dir():
        for f in sorted(rel_dir.glob("*.json")):
            released |= set(json.loads(f.read_text()).get("families", []))

    def stage(n: str) -> str:
        if n in released:
            return "RELEASED"
        f = factory.get(n)
        if not f:
            return "MERGED"
        if f.get("qualified"):
            return "QUALIFIED"
        if f.get("qualified") is False:
            return f"NEEDS_WORK — {f.get('reason', 'see release report')}"
        return "GENERATED"

    n_ref = sum(1 for n in designs if n.startswith("example_"))
    n_real = len(designs) - n_ref
    n_qual = sum(1 for n in designs if stage(n) in ("QUALIFIED", "RELEASED"))
    filled = round(20 * n_real / TARGET)
    bar = "█" * filled + "░" * (20 - filled)

    lines = [
        "# Status",
        "",
        "*Auto-generated by `bench2 status` — do not edit. Stages: MERGED → "
        "GENERATED → QUALIFIED/NEEDS_WORK → RELEASED (see CONTRIBUTING.md rule 4). "
        "In-progress work = the [open PRs](../../../pulls).*",
        "",
        f"**{n_real} / {TARGET} families merged** `{bar}` "
        f"(+{n_ref} reference) · {n_qual} release-qualified · updated {date.today()}",
        "",
        "| Family | Owner | Standard | Instances | Frontier IoU | Stage |",
        "|---|---|---|---|---|---|",
    ]
    for n in designs:
        m, f = meta[n], factory.get(n, {})
        inst = f.get("instances", "—")
        iou = f"{f['frontier_iou']:.2f}" if "frontier_iou" in f else "—"
        owner = m.get("contributor", "—")
        owner = f"@{owner}" if owner and owner not in ("—", "BenchCAD") and not owner.startswith("@") else owner
        lines.append(f"| `{n}` | {owner} | {m.get('standard') or '—'} | {inst} | {iou} | {stage(n)} |")
    lines += ["", "Want a family on this board? → [open family issues](https://github.com/BenchCAD-org/benchcad-2-heldout/issues?q=is%3Aissue+is%3Aopen+label%3Afamily)"]
    return "\n".join(lines) + "\n"


def main(root: Path) -> Path:
    out = root / "docs" / "STATUS.md"
    out.write_text(generate(root))
    return out
